# Admin access is available only inside the container's Unix socket.
local all postgres trust
local daclify_mainnet daclify_mainnet_app scram-sha-256
local daclify_testnet daclify_testnet_app scram-sha-256
local all all reject
host daclify_mainnet daclify_mainnet_app 0.0.0.0/0 scram-sha-256
host daclify_testnet daclify_testnet_app 0.0.0.0/0 scram-sha-256
host all all 0.0.0.0/0 reject
host all all ::/0 reject
